name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest

      - name: Build Docker image
        run: docker build -t rajeshkrish/public-ip-webapp .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker tag rajeshkrish/public-ip-webapp:latest
          docker push rajeshkrish/public-ip-webapp:latest

      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install public-ip-webapp ./public-ip-webapp --namespace default

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#36a64f'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_CHANNEL: '#github-notification'
          SLACK_MESSAGE: 'CI Pipeline status: ${{ job.status }}'
